version: '2'

services:
  backend:
    build: backend
    command: npm run dev
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/db:/usr/src/app/db
    ports:
      - 9000:9000

  frontend:
    build: frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 8000:8000
    depends_on:
      - backend
    environment:
      - ENDPOINT=${ENDPOINT}
